import { StrictMode, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';

function App() {
  const [equipment, setEquipment] = useState('Centrifugal pump');
  const [problem, setProblem] = useState('Discharge pressure is low and the suction strainer alarm is active.');
  const [result, setResult] = useState(null);
  const [documents, setDocuments] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  async function runTroubleshooting(event) {
    event.preventDefault();
    setLoading(true);
    setError('');
    try {
      const response = await fetch(`${API_URL}/api/troubleshoot`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ equipment, problem }),
      });
      if (!response.ok) throw new Error('The assistant could not process this request.');
      setResult(await response.json());
    } catch (requestError) {
      setError(`${requestError.message} Is the FastAPI service running on port 8000?`);
    } finally {
      setLoading(false);
    }
  }

  async function loadDocuments() {
    try {
      const response = await fetch(`${API_URL}/api/documents`);
      if (response.ok) setDocuments(await response.json());
    } catch {
      setDocuments([]);
    }
  }

  return (
    <main className="shell">
      <header className="topbar">
        <div className="brand"><span className="brand-mark">+</span><span>PlantOps <b>AI</b></span></div>
        <div className="system-status"><span className="status-dot" /> Assistant online <span className="divider" /> RAG index ready</div>
      </header>

      <section className="intro">
        <div>
          <p className="eyebrow">Operations intelligence / 01</p>
          <h1>Find the signal<br /><em>before the shutdown.</em></h1>
          <p className="lede">Describe an equipment condition. PlantOps AI will ground its response in your procedures and show exactly where the recommendation came from.</p>
        </div>
        <div className="intro-note"><span>●</span><p>Designed for the control room<br /><small>Traceable answers. No black boxes.</small></p></div>
      </section>

      <div className="workspace">
        <section className="panel query-panel">
          <div className="panel-heading"><span className="step">01</span><div><h2>Describe the condition</h2><p>Use the equipment tag, alarm, or symptom.</p></div></div>
          <form onSubmit={runTroubleshooting}>
            <label>Equipment or asset
              <input value={equipment} onChange={(event) => setEquipment(event.target.value)} placeholder="e.g. Compressor K-301" />
            </label>
            <label>What are you seeing?
              <textarea value={problem} onChange={(event) => setProblem(event.target.value)} rows="6" placeholder="Describe the condition, alarm, and recent changes..." />
            </label>
            <button className="primary-button" type="submit" disabled={loading}>{loading ? 'Analyzing...' : 'Generate troubleshooting path'} <span>→</span></button>
          </form>
          {error && <p className="error">{error}</p>}
          <div className="quick-cases"><span>Try a case</span><button type="button" onClick={() => { setEquipment('Compressor'); setProblem('High vibration alarm is rising on the compressor.'); }}>High vibration</button><button type="button" onClick={() => { setEquipment('Heat exchanger'); setProblem('Outlet temperature is drifting above the normal operating range.'); }}>Temperature drift</button></div>
        </section>

        <section className="panel result-panel">
          <div className="panel-heading"><span className="step">02</span><div><h2>Recommended path</h2><p>AI-assisted, procedure-grounded response.</p></div></div>
          {!result ? <div className="empty-state"><div className="pulse-mark">+</div><h3>Awaiting an equipment condition</h3><p>Your recommendation and source trail will appear here.</p></div> : <div className="result-content">
            <div className="severity-row"><span className={`severity ${result.severity}`}>{result.severity} priority</span><span className="generated">Generated by {result.generated_by}</span></div>
            <p className="answer">{result.answer}</p>
            <div className="checks"><h3>Next checks</h3>{result.next_checks.map((check, index) => <div className="check" key={check}><span>{String(index + 1).padStart(2, '0')}</span><p>{check}</p></div>)}</div>
            <div className="sources"><div className="source-heading"><h3>Source trail</h3><span>{result.sources.length} matched procedures</span></div>{result.sources.map((source) => <article className="source" key={source.id}><div><strong>{source.title}</strong><span>{source.equipment} · relevance {Math.round(source.score * 100)}%</span></div><p>“{source.excerpt}”</p></article>)}</div>
          </div>}
        </section>
      </div>

      <section className="library-strip"><div><p className="eyebrow">Knowledge base</p><h2>Procedure library</h2><p>Documents indexed for grounded retrieval.</p></div><button className="secondary-button" type="button" onClick={loadDocuments}>Refresh library <span>↗</span></button><div className="library-count">{documents.length || '03'}<small>procedures available</small></div></section>
      <footer><span>PLANTOPS AI · v0.1</span><span>Responses require operator verification before action.</span></footer>
    </main>
  );
}

createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>);
